"""Fix enum defaults

Revision ID: 2651365ce744
Revises: c3aa4f28b41a
Create Date: 2025-06-01 18:16:09.165299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2651365ce744'
down_revision = 'c3aa4f28b41a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 