"""Add email and password_hash to developers

Revision ID: 5fe8242f06c4
Revises: 79c4983ebe42
Create Date: 2025-06-01 18:01:41.802902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe8242f06c4'
down_revision = '79c4983ebe42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('developers', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_developers_user_id'), table_name='developers')
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.drop_constraint(op.f('developers_user_id_fkey'), 'developers', type_='foreignkey')
    op.drop_column('developers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('developers_user_id_fkey'), 'developers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.create_index(op.f('ix_developers_user_id'), 'developers', ['user_id'], unique=True)
    op.drop_column('developers', 'password_hash')
    op.drop_column('developers', 'email')
    # ### end Alembic commands ### 