"""Initial schema with corrected enums

Revision ID: c3aa4f28b41a
Revises: 5fe8242f06c4
Create Date: 2025-06-01 18:12:42.546144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa4f28b41a'
down_revision = '5fe8242f06c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 