"""Fix enum definitions with values_callable

Revision ID: eebabbd703c5
Revises: 2651365ce744
Create Date: 2025-06-01 18:22:24.376104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eebabbd703c5'
down_revision = '2651365ce744'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status'),
               nullable=True)
    # ### end Alembic commands ### 